BviNewsBundle\Entity\News:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [title]
            message: "Title already exists."
    properties:
        title:
           - NotBlank:
                message: "Please enter title."
        content:
           - NotBlank:
                message: "Please enter content."
        status:
            - NotBlank:
                message: "Please select status."