<?php

namespace BviNewsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function getList($params = array()) {
        
        $query      = $this->createQueryBuilder('nm');
        $refineQtr  = $this->prepareFilters($query,$params);
        
        return $refineQtr;
        
    }
    
    //prepare filter operation
    
    public function prepareFilters($query,$params) {
        
        $sortOrd= 'desc'; $sortBy = 'nm.id';
        
        if(isset($params['title']) && $params['title']!='') {
            $query->where( $query->expr()->like('nm.title', ':TITLE'));
            $query->setParameter('TITLE','%'.$params['title'].'%');
        }
        if(isset($params['status']) && $params['status']!='') {
            $query->andWhere('nm.status=:STATUS');
            $query->setParameter('STATUS',$params['status']);
        }
        if(isset($params['sortBy']) && $params['sortBy']!='') {
            $sortBy = 'nm.'.$params['sortBy'];
        }
        if(isset($params['sortOrd']) && $params['sortOrd']!='') {
            $sortOrd = $params['sortOrd'];
        }
        
        $query->orderBy($sortBy, $sortOrd);
       # echo $query->getQuery()->getSql();die;
        return $query;
    }
}
